<?php
return [
    'class' => 'frontend\base\components\UrlManager',
    'enablePrettyUrl' => true,
    'showScriptName' => false,
    'enableStrictParsing' => false,
    'suffix' => '/',
    'rules' => [
        ['pattern' => '',                                               'route' => 'site/index'],
        ['pattern' => 'category/<slug:[\w-]+>',                         'route' => 'category/index'],
        ['pattern' => 'category/<action>',                              'route' => 'category/<action>'],
        ['pattern' => 'product/<slug:[\w-]+>',                          'route' => 'product/index'],
        ['pattern' => 'product/<action>',                               'route' => 'product/<action>'],
        ['pattern' => 'podarochnye-nabory/<slug:[\w-]+>',               'route' => 'package/index'],
        ['pattern' => 'podarochnyj-nabor/<slug:[\w-]+>',                'route' => 'package/package'],
        ['pattern' => 'podarochnye-nabory/tag/<slug:[\w-]+>',           'route' => 'package/tag'],
        ['pattern' => 'podarochnye-nabory/<action>',                    'route' => 'package/<action>'],
        ['pattern' => 'shopcart/',                                      'route' => 'shopcart/index'],
        ['pattern' => 'shopcart/<id:\d+>/add',                          'route' => 'shopcart/add'],
        ['pattern' => 'shopcart/<action>',                              'route' => 'shopcart/<action>'],
        ['pattern' => 'payment/<action>',                               'route' => 'payment/<action>'],
        ['pattern' => 'review/',                                        'route' => 'review/index'],
        ['pattern' => 'review/<action>',                                'route' => 'review/<action>'],
        ['pattern' => 'news/',                                          'route' => 'news/index'],
        ['pattern' => 'news/<slug:[\w-]+>',                             'route' => 'news/news'],
        ['pattern' => 'news/<action>',                                  'route' => 'news/<action>'],
        ['pattern' => 'magazine/',                                      'route' => 'magazine/index'],
        ['pattern' => 'magazine/<slug:[\w-]+>',                         'route' => 'magazine/magazine'],
        ['pattern' => 'magazine/<action>',                              'route' => 'magazine/<action>'],
        ['pattern' => 'sitemap.xml',                                    'route' => 'sitemap/index', 'suffix' => ''],
//        ['pattern' => '404/',                                           'route' => 'site/not-found'],
        ['pattern' => '<action>',                                       'route' => 'site/<action>'],
    ],
];
