<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'New Password' => 'Новый пароль',
    'Repeat New Password' => 'Повторите новый пароль',
    'Admin Panel' => 'Админ Панель',
    'Configuration' => 'Настройки',
    'Create' => 'Создать',
    'Create {modelClass}' => 'Создать {modelClass}',
    'Home' => 'Главная',
    'Login' => 'Вход',
    'Logout ({user})' => 'Выход ({user})',
    'Please fill out the following fields to login:' => 'Пожалуйста, заполните следующие поля:',
    'Update' => 'Редактировать',
    'Update {modelClass}: ' => 'Редактировать {modelClass}: ',
    'Delete' => 'Удалить',
    'Users' => 'Пользователи',
    'View {modelClass}: ' => 'Просмотр {modelClass}: ',
    'Welcome to Admin Panel' => 'Добро пожаловать в админ панель',
    'ID' => 'Номер',
    'Name' => 'Название',
    'ImageFile' => 'Картинка',
    'Image Product First' => 'Картинка для первой банки мёда',
    'Image Product Second' => 'Картинка для второй банки мёда',
    'Description' => 'Полное описание',
    'Position' => 'Позиция',
    'Slug' => 'Альяс',
    'CreatedAt' => 'Время создания',
    'PublicAt' => 'Дата публикаци',
    'UpdateAt' => 'Время последнего изменения',
    'Category' => 'Категория',
    'Category Id' => 'Категория продукта',
    'Short Description' => 'Краткое описание',
    'Product ID' => 'Продукт',
    'Volume' => 'Объём тары',
    'Price' => 'Цена',
    'Price Product First' => 'Цена первой банки мёда',
    'Price Product Second' => 'Цена второй банки мёда',
    'photosModels' => 'Изображения для подарочных наборов',
    'Volumes' => 'Объемы тары',
    'Type Delivery' => 'Способ доставки',
    'Name Buyer' => 'Имя',
    'E-mail' => 'E-mail',
    'Phone' => 'Телефон',
    'Type Payment' => 'Способ оплаты',
    'Total Count' => 'Общая стоимость с доставкой',
    'Order ID' => 'Номер заказа',
    'Status' => 'Статус оплаты',
    'Token' => 'Токен',
    'Result' => 'Результат',
    'Notification' => 'Уведомление',
    'Error' => 'Ошибка',
    'Type' => 'Тип',
    'Url' => 'url',
    'Url for Soc' => 'Ссылка насоциальную сеть',
    'Review' => 'Отзыв',
    'For main' => 'На главную',
    'Active' => 'Активный(ая)',
    'Description Top' => 'Верхнее описание',
    'Description Bottom' => 'Нижнее описание',
    'Title Page' => 'Заголовок страницы',
    'Name Page' => 'Название страницы',
    'Name Fixed' => 'Фиксированое имя',
    'Description Meta' => 'Description meta-tag',
    'Tag H1' => 'Тег H1',
    'Content' => 'Содержание страницы',
    'Title News' => 'Заголовок новости',
    'Title Magazine' => 'Заголовок журнала',
    'Title' => 'Заголовок',
    'Url For Page' => 'Url для страницы',
];
