<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'New password for {applicationName}' => 'Новый пароль для {applicationName}',
    'Password reset for {applicationName}' => 'Сброс пароля на {applicationName}',
    'Registration on {applicationName}' => 'Регистрация на {applicationName}',
    'You have been registered in the {applicationName} project.' => 'Вы были зарегистрированы в проекте {applicationName}.',
    'Your new password: {password}.' => 'Ваш новый пароль: {password}.',
    'Your password in the {applicationName} project has been changed.' => 'Ваш пароль в проекте {applicationName} был изменен.',
    'Active' => 'Активный',
    'Admin' => 'Админ',
    'Auth Key' => 'Ключ авторизации',
    'Blocked' => 'Заблокирован',
    'Created At' => 'Дата создания',
    'User' => 'Пользователь',
    'E-Mail' => 'E-Mail',
    'Follow the link below to reset your password:' => 'Перейдите по ссылке ниже, чтобы восстановить пароль:',
    'Hello {username}' => 'Здравствуйте, {username}',
    'ID' => 'ID',
    'Incorrect username or password.' => 'Неправильный логин или пароль.',
    'Password' => 'Пароль',
    'Password Hash' => 'Хеш пароля',
    'Password Reset Token' => 'Токен сброса пароля',
    'Remember Me' => 'Запомнить этот компьютер',
    'Role' => 'Роль',
    'Status' => 'Статус',
    'Updated At' => 'Дата изменения',
    'Username' => 'Имя пользователя',
    'Url for Soc' => 'Ссылка на в соц. сеть',
];
